version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env.dev
    environment:
      - ENV=dev
    restart: unless-stopped 